export const traceplusLogo = 'http://iot.orvito.com:6220/assets/img/icons/sidebar/trace_logo.png'
export const peopleOnPremisesIcon = 'http://iot.orvito.com:6220/assets/img/icons/dashboard/people_on_premises_icon.svg'
export const downThumbIcon = "http://iot.orvito.com:6220/assets/img/icons/dashboard/orange_thumb.svg"
export const greenThumbIcon = "http://iot.orvito.com:6200/assets/img/icons/dashboard/green_thumb.svg"
export const dashboardPeopleImage = "http://iot.orvito.com:6220/assets/img/icons/dashboard/threat_watch_orange_img.svg"
export const pinkArrowIcon = "http://iot.orvito.com:6220/assets/img/icons/dashboard/pink_outline_right_arrow_icon.svg"
export const selectedPinkArrowIcon = "http://iot.orvito.com:6200/assets/img/icons/dashboard/pink_right_arrow_icon.svg"
export const showPasswordEyeIcon = "http://iot.orvito.com:6200/assets/img/icons/login/show_password.png"
export const tagIcon = "http://iot.orvito.com:6200/assets/img/icons/common/tag_icon.svg"
export const mediumRiskIcon = "http://iot.orvito.com:6200/assets/img/icons/manpower/medium_risk_icon.svg"
export const dayShiftImage = "http://iot.orvito.com:6200/assets/img/icons/manpower/sun.svg"
export const emailIcon = "http://iot.orvito.com:6200/assets/img/icons/manpower/employee_email_icon.svg"
export const empIDIcon= "http://iot.orvito.com:6200/assets/img/icons/manpower/employee_id_icon.svg"
export const batteryIcon = "http://iot.orvito.com:6200/assets/img/icons/manpower/battery.svg"
